# Generated by Django 5.0 on 2023-12-07 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaskInWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.tasks')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.taskstatus')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.users')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.usertypes'),
        ),
    ]
