# Generated by Django 5.0 on 2023-12-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='notexist', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default='notexist', max_length=30),
            preserve_default=False,
        ),
    ]
